double_sodas = [ ("kiwwi_menta", "Kiwwi-menta", "Kiwwi-menta", 6500),
                 ("limonada_coco", "Limo coco", "Limonada de coco", 6500),
                 ("menta_marac", "Menta marac", "Menta-maracuyá", 6500),
                 ("sandia_hierb", "Sandia hierb", "Sandia-hierbabuena", 6500),
                 ("mango_duraz", "Mango dur", "Mango-durazno", 6500),
                 ("sandia_pepin", "Sandia pep", "Sandia-pepino", 6500),
                 ("mango_lyme", "Mango lyme", "Mango-lyme habanero", 6500),
                 ("lychee_menta", "Lychee menta", "Lychee-menta", 6500),
                 ("personalized", "Personal", "Personalizada", 6500) ]

sodas = [ ("durazno", "Durazno", "Durazno", 6000),
          ("pepino", "Pepino", "Pepino", 6000),
          ("manzana_verde", "Manzana", "Manzana verde", 6000),
          ("coco", "Coco", "Coco", 6000),
          ("mango", "Mango", "Mango", 6000),
          ("fresa", "Fresa", "Fresa", 6000),
          ("sandia", "Sandia", "Sandia", 6000),
          ("mora_azul", "Mora azul", "Mora azul", 6000),
          ("menta", "Menta", "Menta", 6000),
          ("lychee", "Lychee", "Lychee", 6000),
          ("lyme_haban", "Lyme haban", "Lyme habanero", 6000),
          ("maracuya", "Maracuyá", "Maracuyá", 6000),
          ("amarena", "Amarena", "Amarena", 6000),
          ("kiwwi", "Kiwwi", "Kiwwi", 6000) ]

additions = [ ("add_lychee", "A Lychee", "Lychee", 800),
              ("add_durazno", "A Durazno", "Durazno", 800),
              ("add_mix_fruto", "A Mix frutos", "Mix frutos rojos", 800),
              ("add_mango", "A Mango", "Mango", 500),
              ("add_fresa", "A Fresa", "Fresa", 500),
              ("add_maracuya", "A Maracuyá", "Maracuyá", 500),
              ("add_coco", "A Coco", "Coco", 500),
              ("add_cereza", "A Cereza", "Cereza", 500),
              ("add_explosion", "A Explosión", "Explosión", 800),
              ("add_jelly_arco", "A Jelly", "jelly arcoiris", 800) ]

bakery = [ ("pastel_pollo", "P Pollo", "Pastel de pollo", 3800),
           ("pastel_carne", "P Carne", "Pastel carne", 3800),
           ("croissant_queso", "C queso", "Croissant queso", 3000),
           ("croissant_peppe", "C peperon", "Croissant pepperoni mozzarella y oregano", 3800),
           ("croissant_pesto", "C pesto", "Croissant pesto y cebolla caramelizada", 4000),
           ("rollo_espin", "R espin", "Rollo de Espinaca", 3600),
           ("palito_queso", "P 3 quesos", "Palito 3 quesos", 3800),
           ("palito_super", "P super", "Palito super perro", 4600),
           ("rollo_canel", "R canela", "Rollo de canela", 3000),
           ("rollo_nutel", "R nutella", "Rollo de nutella", 3000) ]

coffe = [ ("capuchino", "Capuchino", "Capuchino", 60000),
          ("expresso", "Expresso", "Expresso", 100000),
          ("cafe_ameri", "Americano", "Café americano", 200000),
          ("mocaccino", "Mocaccino", "Mocaccino", 1234578),
          ("chocolate", "Chocolate", "Chocolate", 400000),
          ("chocolate_leche", "Choco leche", "chocolate en leche", 500000) ]
